server:
  port: 8000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: products-service
              uri: lb://PRODUCTS-SERVICE
              predicates:
                - Path=/products/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders/**